services:
  - type: web
    name: rtc-scheduler-demo
    runtime: static
    buildCommand: echo "No build needed"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /index.html
